version: "3.7"
services:
  node:
    container_name: twilio-bodypix-test
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always    
    networks:
      - default
      - shared-network
networks:
  shared-network:
    external: true